### ISSUE TITLE
Extracting date and time code gives NA

### ISSUE THREAD

**Issue by LohithArcot** [MJFND/R#1]
#Extracting date and time  
`date_time <- format(strptime(all_data, "%m/%d/%y, %I:%M %p"),"%m/%d/%y, %H:%M")`
The above line gives out NA's in the date_time.
I believe this is because the whatsapp chat gets saved in a different time format. i.e %d/%m/%Y and not %m/%d/%y . 
The strptime needs to be changed accordingly and works fine after that. Similarly the time format too needs to be corrected.

**Comment by MJFND** [comment]
First of all thanks for revealing this issue.
After a little research, its a problem of the timezone format that your mobile follows. I follow a US based format so it gave me that, I also cross checked from other country and that gave me your format. 
Same goes with timestamp, US based does not have second in the stamp, but other one does.

So it should be changed to what your chat have, I will update the code. 

Thanks
